### ISSUE TITLE
WireGuard Integration Using Unsupported Method

### ISSUE THREAD

**Issue by zx2c4** [tbalden/htc-kernel-pmewlvzw#2]
Some important WireGuard changes you might have missed...

You've been building WireGuard as part of this kernel by actually committing the WireGuard source code. *Please stop doing this*, and instead move over to the new method, which was created in response to a few recent requests and concerns. It's also an *important* thing to do, because it ensures that things actually stay up to date. [The below instructions follow from "Standalone Kernel Built-in Module" in the documentation.](https://git.zx2c4.com/android_kernel_wireguard/about/)

First remove what you did before:

```
$ rm -rf path/to/kernel/net/wireguard # or just revert your previous commit
```

Now run the persistent patcher script and commit its results:

```
$ cd /tmp && git clone https://git.zx2c4.com/android_kernel_wireguard/
$ cd android_kernel_wireguard/standalone-kernel
$ ./patch-kernel.sh path/to/kernel
$ cd /tmp && rm -rf android_kernel_wireguard
$ cd path/to/kernel && git add . && git commit -m "net/wireguard: add to tree via updater mechanism"
```

That should be all that's required.

**Comment by tbalden** [comment]
It's obligatory for my legal obligation to provide full sources to reproduce distributed binary.
That's intentionally so and I'm sticking with it because I still update while building next release and push changes.

**Comment by zx2c4** [comment]
Legally, that's not the case, actually. The full sources are still provided and readily available when you use the officially supported method. The sources are also directly linked by your kernel tree. (If you were correct, nobody would use git submodules, for example, of which the fetcher here is a more sophisticated version.)

Please use an officially supported method of integrating WireGuard.

**Comment by tbalden** [comment]
I see. Tell me tho, why is it a problem? Each build still uses your script, I'm just making sure there's a source for each given build, and fully reproducible the binaries I provide. Is there an information in the kernel binary and resulting execution environment from which the user can exactly identify which tag was used from your tree for the given built binary?

**Comment by zx2c4** [comment]
Yes, a user can always run this to learn what's running:
```
# cat /sys/module/wireguard/version 
0.0.20171211
```

Or, alternatively:
```
# dmesg | grep wireguard
```

**Comment by tbalden** [comment]
Ok, that's reasonable. Will get back to use exclusion in. gitignore and
remove it.
Thanks

**Comment by tbalden** [comment]
done
